openapi: 3.0.0
info:
  title: Authentication API
  description: API documentation for user authentication
  version: 1.0.0

paths:
  /profile:
    get:
      tags:
        - Profile
      summary: Get user profile
      parameters:
        - in: header
          name: Authorization
          required: true
          schema:
            type: string
          description: Bearer token
      responses:
        '200':
          description: Successful response with user profile
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserProfile'
        '401':
          description: Unauthorized access
          
components:
  schemas:
    UserProfile:
      type: object
      properties:
        email:
          type: string
          example: arman.mikoyan1@gmail.com
        username:
          type: string
          example: arman.mikoyan
